from typing import List, Dict, Any
from llm_client import LLMClient, is_llm_available, polish_text
from tools.role_database import get_role_requirements

class PortfolioProjectAgent:
    """
    PortfolioProjectAgent designs and schedules high-impact portfolio projects
    specifically optimized to demonstrate missing skill requirements.
    """
    def __init__(self, llm_client: LLMClient = None):
        self.llm = llm_client or LLMClient()
        self.name = "Portfolio Project Agent"

    def recommend_project(self, gaps: List[str], target_role: str) -> dict:
        """
        Recommends a detailed portfolio project tailored to missing skills and the target role.
        """
        role_reqs = get_role_requirements(target_role)
        rec_projects = role_reqs.get("recommended_projects", [])
        
        # Determine the base details of the project
        # Define detailed project definitions for fallback
        db_projects = {
            "AI/ML Intern": {
                "title": "Customer Churn Prediction Pipeline",
                "problem": "Companies struggle to predict customer retention. This project constructs an end-to-end ML model pipeline to classify at-risk users, helping businesses proactively reduce churn.",
                "features": [
                    "Data preprocessing pipeline utilizing Pandas for scaling and handling missing inputs.",
                    "Imbalance mitigation using synthetic data oversampling.",
                    "Model training workflow with Scikit-Learn Random Forest or Gradient Boosting.",
                    "FastAPI REST endpoint to serve predictions.",
                    "Dockerfile packaging for model api deployment."
                ],
                "tech_stack": ["Python", "Pandas", "Scikit-Learn", "FastAPI", "Docker", "Git"],
                "dataset_idea": "Synthetically generated transaction records (CSV) with features like customer age, monthly bills, activity frequency, and churn status.",
                "folder_structure": (
                    "churn-prediction-pipeline/\n"
                    "├── data/\n"
                    "│   └── churn_sample.csv\n"
                    "├── src/\n"
                    "│   ├── preprocess.py\n"
                    "│   ├── train.py\n"
                    "│   └── app.py\n"
                    "├── tests/\n"
                    "│   └── test_api.py\n"
                    "├── Dockerfile\n"
                    "├── requirements.txt\n"
                    "└── README.md"
                ),
                "demo_plan": "Run model training in src/train.py. Start the API using 'uvicorn src.app:app --reload'. Call POST to /predict with test client records to see prediction results."
            },
            "Data Analyst Intern": {
                "title": "E-Commerce Sales Performance Analytics Dashboard",
                "problem": "Operational teams lack visual insights into historical transaction patterns and user cohorts, leading to slow business decisions.",
                "features": [
                    "PostgreSQL schema modeling and transaction record loading.",
                    "Complex SQL window functions calculating year-over-year growth and user cohorts.",
                    "Python scripts to aggregate, clean, and validate daily reports.",
                    "Interactive visualization worksheets built with Tableau or Matplotlib/Seaborn."
                ],
                "tech_stack": ["SQL", "PostgreSQL", "Python", "Pandas", "Excel", "Git"],
                "dataset_idea": "Kaggle online retail dataset with attributes like Order ID, Customer ID, Date, Amount, and Category.",
                "folder_structure": (
                    "ecommerce-sales-analytics/\n"
                    "├── sql/\n"
                    "│   ├── schema.sql\n"
                    "│   └── queries.sql\n"
                    "├── notebooks/\n"
                    "│   └── data_cleaning.ipynb\n"
                    "├── data/\n"
                    "│   └── retail_transactions.csv\n"
                    "├── requirements.txt\n"
                    "└── README.md"
                ),
                "demo_plan": "Initialize schema, execute SQL queries to fetch KPI metrics, and view visualizations generated by the notebooks."
            },
            "Python Developer Intern": {
                "title": "Asynchronous Task Queue API",
                "problem": "Heavy computations blocks synchronous API servers. This project uses Celery and Redis to handle tasks in the background, minimizing REST latency.",
                "features": [
                    "FastAPI endpoints with asynchronous routing handlers.",
                    "Celery task runner utilizing Redis as a message broker.",
                    "SQLite/SQLModel storage database for task persistence.",
                    "Comprehensive unit tests matching 80%+ coverage with pytest."
                ],
                "tech_stack": ["Python", "FastAPI", "Redis", "Celery", "Docker", "pytest", "SQLite", "Git"],
                "dataset_idea": "Simulated task queue loads (e.g. data encoding, PDF compilation requests).",
                "folder_structure": (
                    "async-task-queue/\n"
                    "├── app/\n"
                    "│   ├── main.py\n"
                    "│   ├── tasks.py\n"
                    "│   └── config.py\n"
                    "├── tests/\n"
                    "│   └── test_tasks.py\n"
                    "├── Dockerfile\n"
                    "├── docker-compose.yml\n"
                    "├── requirements.txt\n"
                    "└── README.md"
                ),
                "demo_plan": "Run 'docker-compose up'. Call POST to /tasks to enqueue a task, and run GET to /tasks/{id} to track execution status. Execute 'pytest' to view test suite success."
            },
            "Web Developer Intern": {
                "title": "Collaborative Kanban Board",
                "problem": "Team members require an interactive interface to transition task statuses, but building cross-origin state synchronization is difficult.",
                "features": [
                    "React client app featuring responsive layout grids and state management.",
                    "Drag-and-drop actions to change task stages.",
                    "Node.js & Express REST server hosting task controllers.",
                    "MongoDB database schema storage."
                ],
                "tech_stack": ["React.js", "JavaScript", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "Git"],
                "dataset_idea": "User task document collections containing task ID, title, description, column, and owner.",
                "folder_structure": (
                    "kanban-board/\n"
                    "├── client/\n"
                    "│   ├── public/\n"
                    "│   └── src/\n"
                    "│       ├── components/\n"
                    "│       └── App.js\n"
                    "├── server/\n"
                    "│   ├── models/\n"
                    "│   ├── routes/\n"
                    "│   └── server.js\n"
                    "├── package.json\n"
                    "└── README.md"
                ),
                "demo_plan": "Run 'npm install' and 'npm start' in both client and server directories. Open http://localhost:3000 to manage Kanban cards and verify data updates in MongoDB."
            },
            "GenAI Intern": {
                "title": "RAG-Based Documentation Q&A Bot",
                "problem": "Users struggle to digest dense manuals or developer documentation. This project uses vector databases and LLM APIs to answer questions grounded in specific PDF manuals.",
                "features": [
                    "PDF parser split into semantic chunks using LangChain.",
                    "Vector index generation stored using ChromaDB.",
                    "Question retrieval matched via cosine similarity.",
                    "Interactive chat layout using Streamlit."
                ],
                "tech_stack": ["Python", "LangChain", "ChromaDB", "Gemini API", "Streamlit", "Git"],
                "dataset_idea": "Developer documentation PDF manuals.",
                "folder_structure": (
                    "rag-doc-bot/\n"
                    "├── data/\n"
                    "│   └── docs/\n"
                    "│       └── sample_manual.pdf\n"
                    "├── app/\n"
                    "│   ├── main.py\n"
                    "│   └── rag_engine.py\n"
                    "├── tests/\n"
                    "│   └── test_rag.py\n"
                    "├── requirements.txt\n"
                    "└── README.md"
                ),
                "demo_plan": "Run 'streamlit run app/main.py'. Upload a sample PDF document, query the chatbot about its content, and see the answers generated along with source chunks."
            }
        }

        # Select matching template, fallback if role is not direct match
        project_info = db_projects.get(target_role)
        if not project_info:
            # Try partial matching of target_role string
            matched = False
            for k, val in db_projects.items():
                if k.lower() in target_role.lower() or target_role.lower() in k.lower():
                    project_info = val
                    matched = True
                    break
            
            if not matched:
                # Default generic fallback
                project_info = {
                    "title": "SkillBridge Portfolio Showcase Project",
                    "problem": "Students need a single, comprehensive capstone project that proves their competency in core software engineering principles.",
                    "features": [
                        "Automated scripts executing core features.",
                        "Database/file storage layer.",
                        "Clean REST endpoints or command-line interface.",
                        "Unit testing coverage using pytest."
                    ],
                    "tech_stack": ["Python", "Git", "SQLite", "pytest"],
                    "dataset_idea": "Mock structured metadata database.",
                    "folder_structure": (
                        "portfolio-showcase/\n"
                        "├── src/\n"
                        "│   └── main.py\n"
                        "├── tests/\n"
                        "│   └── test_main.py\n"
                        "├── requirements.txt\n"
                        "└── README.md"
                    ),
                    "demo_plan": "Run 'python src/main.py' to launch, and 'pytest' to verify unit testing."
                }

        # Enrich project details based on recommended projects from JSON database if available
        if rec_projects:
            # Override title/description/tech_stack using database details if desired
            db_proj = rec_projects[0]
            project_info["title"] = db_proj.get("name", project_info["title"])
            project_info["problem"] = f"A project designed to cover critical internship requirements. Description: {db_proj.get('description', project_info['problem'])}"
            project_info["tech_stack"] = db_proj.get("tech_stack", project_info["tech_stack"])

        # Construct final dict
        result = {
            "project_name": project_info["title"], # Keep 'project_name' for compatibility
            "title": project_info["title"],
            "problem": project_info["problem"],
            "features": project_info["features"],
            "tech_stack": project_info["tech_stack"],
            "dataset_idea": project_info["dataset_idea"],
            "folder_structure": project_info["folder_structure"],
            "demo_plan": project_info["demo_plan"],
            "complexity": "Intermediate"
        }

        # Call LLM for custom recommendations if API key is active
        if is_llm_available():
            prompt = (
                f"Design a highly tailored portfolio project for a student with gaps: {gaps} targeting the role {target_role}.\n"
                f"Suggested basic details:\n{result}\n"
                f"Return a JSON format or structured representation of: title, problem, features, tech_stack, dataset_idea, folder_structure, demo_plan."
            )
            result["problem"] = polish_text(
                prompt=prompt,
                fallback_text=result["problem"],
                system_instruction="You are a senior tech lead. Return a detailed project specification tailored to candidate gaps."
            )

        return result
